# https://taskfile.dev

version: "3"

tasks:
  ci:
    desc: Run all the project CI checks
    cmds:
      - task: test
      - task: lint

  test:
    desc: Run the tests
    cmd: go test ./...

  lint:
    desc: Run the linter
    cmd: golangci-lint run
